name: ReleaseCI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [ "viewer-request", "viewer-response", "origin-request", "origin-response" ]
    steps:
    - uses: actions/checkout@v1

    - name: Fetch GH Release Asset
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        version: "tags/master"
        file: "${{ matrix.name }}.js"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Zip
      run: zip ${{ matrix.name }}.zip ${{ matrix.name }}.js

    - name: Release to S3
      run: bash scripts/pipeline/release.sh "prod-techops-edgelambda-artifacts" "${{ matrix.name }}.zip" ${{secrets.AWS_ACCESS_KEY_ID}} ${{secrets.AWS_SECRET_ACCESS_KEY}} "${{ matrix.name }}.zip"