name: ReleaseCI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Fetch GH Release Asset
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        version: "tags/master"
        file: "origin-request.js"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Zip
      run: zip origin-request.zip origin-request.js

    - name: Release to S3
      run: bash scripts/pipeline/release.sh "use1-iac-lambda-artifacts-prod" "origin-request/origin-request.zip" ${{secrets.AWS_ACCESS_KEY_ID}} ${{secrets.AWS_SECRET_ACCESS_KEY}} "origin-request.zip"