name: Test
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Test end-to-end by uploading two artifacts and then downloading them
      # Once upload-artifact v2 is out of preview, switch over
      - name: Create artifacts
        run: |
          mkdir -p ./artifact-A
          mkdir -p ./artifact-B
          echo "Lorem ipsum dolor sit amet" > ./artifact-A/file-A.txt
          echo "Hello world from file B" > ./artifact-B/file-B.txt
    
      - name: Upload artifact A
        uses: actions/upload-artifact@v1
        with:
          name: 'Artifact-A'
          path: ./artifact-A

      - name: Upload artifact B
        uses: actions/upload-artifact@v1
        with:
          name: 'Artifact-B'
          path: ./artifact-B

      # Test downloading a single artifact
      - name: Download artifact A
        uses: actions/download-artifact@v1
        with:
          name: 'Artifact-A'
          path: ./DownloadedArtifacts

      - name: Verify successful download
        run: |
          $file1 = "./DownloadedArtifacts/file-A.txt"
          if(!(Test-Path -path $file1))
          {
              Write-Error "Expected files do not exist"
          }
          if(!((Get-Content $file1) -ceq "Lorem ipsum dolor sit amet"))
          {
              Write-Error "File contents of downloaded artifacts are incorrect"
          }
        shell: pwsh

      # Test downloading both artifacts at once
      - name: Download all Artifacts
        uses: ./
        with:
          path: ./alldownloadedartifacts

      - name: Verify successful download
        run: |
          $fileA = "./alldownloadedartifacts/Artifact-A/file-A.txt"
          $fileB = "./alldownloadedartifacts/Artifact-B/file-B.txt"
          if(!(Test-Path -path $fileA) -or !(Test-Path -path $fileB))
          {
              Write-Error "Expected files do not exist"
          }
          if(!((Get-Content $fileA) -ceq "Lorem ipsum dolor sit amet") -or !((Get-Content $fileB) -ceq "Hello world from file B"))
          {
              Write-Error "File contents of downloaded artifacts are incorrect"
          }
        shell: pwsh